steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - "--ciphertext-file=settings.py.enc"
      - "--plaintext-file=settings.py"
      - "--location=global"
      - "--keyring=my-keyring"
      - "--key=settings"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - clouds-build-notifier
      - --region=asia-northeast1
      - --source=.
      - --trigger-topic=cloud-builds
      - --runtime=python39
      - --entry-point=cloud_build_notifier
