steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - clouds-build-notifier
      - --region=asia-northeast1
      - --source=.
      - --trigger-topic=cloud-builds
      - --runtime=python39
      - --entry-point=cloud_build_notifier
      - --service-account=cloud-build-notifier@slackbot-288310.iam.gserviceaccount.com
